### ISSUE TITLE
项目报错了

### ISSUE THREAD

**Issue by WQHASH** [jzfai/vue3-admin-ts#18]
node 版本：16.15.0
pnpm 版本：7.9.0 
游览器报错：
main.ts:37 ReferenceError: $ref is not defined
    at setup (index.vue:88:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5773:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)

**Comment by jzfai** [comment]
already fix it
